version: "3.8"
services:
  server:
    build: ./server
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      front-tier:
        ipv4_address: 172.16.238.11
  salter:
    build: ./salter
    ports:
      - 3000:3000
    networks:
      front-tier:
        ipv4_address: 172.16.238.12
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      front-tier:
        ipv4_address: 172.16.238.10

networks:
  front-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"